Planmenus/Controllers/MDRol_PermisosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Planmenus.Data;
using Planmenus.Data.Entities;
using Planmenus.Models;

namespace Planmenus.Controllers
{
    public class MDRol_PermisosController : Controller
    {
        private readonly Datacontext _context;

        public MDRol_PermisosController(Datacontext context)
        {
            _context = context;
        }

        // GET: MDRol_Permisos
        public async Task<IActionResult> Index(int id_rol)
        {
            var Idrol = 0;
            if (id_rol == 0)
            {
                Idrol = 1;
            }
            else
            {
                Idrol = id_rol;
            }
            ViewData["Idrol2"] = id_rol;
            ViewBag.rol = await _context.Rols.ToListAsync();  
            ViewBag.admin = await (from rolper in _context.Rol_Permisos
                             join rol in _context.Rols on rolper.id_rol equals rol.id_rol
                             join menu in _context.Menuprins on rolper.id_menprin equals menu.id_menprin
                             join subm in _context.Submenus on rolper.id_submenu equals subm.id_submenu
                             where rolper.id_rol == Idrol && rolper.id_menprin == 1
                             select new VMRolpers
                             {
                                 id_rolper = rolper.id_rolper,
                                 //id_rol = rolper.id_rol,
                                 //id_menprin = rolper.id_menprin,
                                 //id_submenu = rolper.id_submenu,
                                 rol_desc = rol.rol_desc,
                                 menuprin_desc = menu.menuprin_desc,
                                 submenu_desc = subm.submenu_desc,
                                 rolper_act = rolper.rolper_act
                             }).ToListAsync();
            ViewBag.plani = await (from rolper in _context.Rol_Permisos
                             join rol in _context.Rols on rolper.id_rol equals rol.id_rol
                             join menu in _context.Menuprins on rolper.id_menprin equals menu.id_menprin
                             join subm in _context.Submenus on rolper.id_submenu equals subm.id_submenu
                             where rolper.id_rol == Idrol && rolper.id_menprin == 2
                             select new VMRolpers
                             {
                                 id_rolper = rolper.id_rolper,
                                 //id_rol = rolper.id_rol,
                                 //id_menprin = rolper.id_menprin,
                                 //id_submenu = rolper.id_submenu,
                                 rol_desc = rol.rol_desc,
                                 menuprin_desc = menu.menuprin_desc,
                                 submenu_desc = subm.submenu_desc,
                                 rolper_act = rolper.rolper_act
                             }).ToListAsync();
            ViewBag.caja  = await (from rolper in _context.Rol_Permisos
                             join rol in _context.Rols on rolper.id_rol equals rol.id_rol
                             join menu in _context.Menuprins on rolper.id_menprin equals menu.id_menprin
                             join subm in _context.Submenus on rolper.id_submenu equals subm.id_submenu
                             where rolper.id_rol == Idrol && rolper.id_menprin == 3
                             select new VMRolpers
                             {
                                 id_rolper = rolper.id_rolper,
                                 //id_rol = rolper.id_rol,
                                 //id_menprin = rolper.id_menprin,
                                 //id_submenu = rolper.id_submenu,
                                 rol_desc = rol.rol_desc,
                                 menuprin_desc = menu.menuprin_desc,
                                 submenu_desc = subm.submenu_desc,
                                 rolper_act = rolper.rolper_act
                             }).ToListAsync();
            return View();
        }

        // GET: MDRol_Permisos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mDRol_Permisos = await _context.Rol_Permisos
                .FirstOrDefaultAsync(m => m.id_rolper == id);
            if (mDRol_Permisos == null)
            {
                return NotFound();
            }

            return View(mDRol_Permisos);
        }

        // GET: MDRol_Permisos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MDRol_Permisos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id_rolper,id_menprin,id_submenu,rolper_act")] MDRol_Permisos mDRol_Permisos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mDRol_Permisos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mDRol_Permisos);
        }

        // GET: MDRol_Permisos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mDRol_Permisos = await _context.Rol_Permisos.FindAsync(id);
            if (mDRol_Permisos == null)
            {
                return NotFound();
            }
            return View(mDRol_Permisos);
        }

        // POST: MDRol_Permisos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id_rolper,id_menprin,id_submenu,rolper_act")] MDRol_Permisos mDRol_Permisos)
        {
            if (id != mDRol_Permisos.id_rolper)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mDRol_Permisos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MDRol_PermisosExists(mDRol_Permisos.id_rolper))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mDRol_Permisos);
        }

        // GET: MDRol_Permisos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mDRol_Permisos = await _context.Rol_Permisos
                .FirstOrDefaultAsync(m => m.id_rolper == id);
            if (mDRol_Permisos == null)
            {
                return NotFound();
            }

            return View(mDRol_Permisos);
        }

        // POST: MDRol_Permisos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mDRol_Permisos = await _context.Rol_Permisos.FindAsync(id);
            _context.Rol_Permisos.Remove(mDRol_Permisos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MDRol_PermisosExists(int id)
        {
            return _context.Rol_Permisos.Any(e => e.id_rolper == id);
        }

        public async Task<ActionResult> otorgar(IEnumerable<int> menus, int Idrol)
        {
            try
            {
                var desact = await _context.Rol_Permisos.Where(x => x.id_rol == Idrol).ToListAsync();
                foreach (var item in desact)
                {
                    var deschek = await _context.Rol_Permisos.Where(z => z.id_rolper == item.id_rolper).SingleOrDefaultAsync();
                    if (deschek != null)
                    {
                        deschek.rolper_act = false;
                        _context.SaveChanges();
                    }
                }
                foreach (var item in menus)
                {
                    var update = await _context.Rol_Permisos.Where(x => x.id_rolper == item).SingleOrDefaultAsync();
                    if (update != null)
                    {
                        update.rolper_act = true;
                        _context.SaveChanges();
                    }
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }

            return View();
        }


    }
}

Planmenus/Views/MDRol_Permisos/Create.cshtml
@model Planmenus.Data.Entities.MDRol_Permisos

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>MDRol_Permisos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="id_menprin" class="control-label"></label>
                <input asp-for="id_menprin" class="form-control" />
                <span asp-validation-for="id_menprin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="id_submenu" class="control-label"></label>
                <input asp-for="id_submenu" class="form-control" />
                <span asp-validation-for="id_submenu" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="rolper_act" /> @Html.DisplayNameFor(model => model.rolper_act)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Planmenus/Views/MDRol_Permisos/Delete.cshtml
@model Planmenus.Data.Entities.MDRol_Permisos

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MDRol_Permisos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id_menprin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id_menprin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id_submenu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id_submenu)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.rolper_act)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.rolper_act)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id_rolper" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Planmenus/Views/MDRol_Permisos/Details.cshtml
@model Planmenus.Data.Entities.MDRol_Permisos

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>MDRol_Permisos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id_menprin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id_menprin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id_submenu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id_submenu)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.rolper_act)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.rolper_act)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id_rolper">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Planmenus/Views/MDRol_Permisos/Edit.cshtml
@model Planmenus.Data.Entities.MDRol_Permisos

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>MDRol_Permisos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id_rolper" />
            <div class="form-group">
                <label asp-for="id_menprin" class="control-label"></label>
                <input asp-for="id_menprin" class="form-control" />
                <span asp-validation-for="id_menprin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="id_submenu" class="control-label"></label>
                <input asp-for="id_submenu" class="form-control" />
                <span asp-validation-for="id_submenu" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="rolper_act" /> @Html.DisplayNameFor(model => model.rolper_act)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Planmenus/Views/MDRol_Permisos/Index.cshtml
@model IEnumerable<Planmenus.Data.Entities.MDRol_Permisos>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css" />
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</head>

<div class="container">
    <div class="card">
      <div class="card-header">
			 <div class="div-title">
				<h3 class="text-center">ROL PERMISOS</h3>
			 </div>
			 <hr />
			 <br />	
            @using (Html.BeginForm())
            {
				<div class="row">					
					<div class="form-group col">
						<input type="hidden" name="Idrol2" id="Idrol2" value="@ViewData["Idrol2"]" />
						<label class="control-label">Roles: </label>
						<select class="form-control" id="id_rol" name="id_rol" asp-items="@(new SelectList(ViewBag.rol, "id_rol", "rol_desc"))">
                            <option>Seleccione rol</option>
                        </select>					
					</div>
				</div>	
				<div class="row">
					 <div class="col-md-6">					
						<input type="submit" value="Buscar" class="btn btn-primary btn-sm" formaction="@Url.Action("Index","MDRol_Permisos")" />
						<input type="submit" id="asignar" value="Asignar" class="btn btn-primary btn-sm"/>
					</div>	
				</div>
			}
		</div>
        <div id="checkid" class="card-body">
            <div class="col">
                 <nav>
                     <div class="nav nav-tabs nav-fill" role="tablist">
                        <a class="nav-item nav-link active" data-toggle="tab" href="#nav-admin" role="tab" aria-selected="true">Administracion</a>
                        <a class="nav-item nav-link" data-toggle="tab" href="#nav-plani" role="tab" aria-controls="nav-plani" aria-selected="false">Planificacion</a>
                        <a class="nav-item nav-link" data-toggle="tab" href="#nav-caja" role="tab" aria-controls="nav-caja"  aria-selected="false">Caja</a>
                    </div>
                 </nav>
                 <div id="checkid" class="tab-content">
                     <div class="tab-pane fade show active" id="nav-admin" role="tabpanel">
						<table  id="tbladmin" class="table table-striped table-bordered" style="width: 100%">
							<thead>
								<tr>
									<th class="d-none">
										id_rolper
									</th>
									<th>
										Rol
									</th>
									<th>
										Menu
									</th>
									<th>
										Submenu
									</th>
									<th>
										Activo / Inactivo
									</th>
								</tr>	
							</thead>														
							<tbody>
								@foreach (var item in ViewBag.admin)
								{
									<tr>
										<td class="d-none check">
											@item.id_rolper
										</td>
										<td>
											@item.rol_desc
										</td>
										<td>
											@item.menuprin_desc
										</td>
										<td>
											@item.submenu_desc
										</td>
										<td>
											@if(item.rolper_act)
											{
												<input name="check" type="checkbox" value=@item.id_rolper checked="checked" />
											}
											else
											{
												<input name="check" type="checkbox" value=@item.id_rolper />
											}										
										</td>
									</tr>
								}
							</tbody>
						</table>
					</div>
					<div class="tab-pane fade" id="nav-plani" role="tabpanel">
						<table id="tblplani" class="table table-striped table-bordered" style="width: 100%">
							<thead>
								<tr>
									<th class="d-none">
										id_rolper
									</th>
									<th>
										Rol
									</th>
									<th>
										Menu
									</th>
									<th>
										Submenu
									</th>
									<th>
										Activo / Inactivo
									</th>
								</tr>
							</thead>							
							<tbody>
								@foreach (var item in ViewBag.plani)
								{
									<tr>
										<td class="d-none check">
											@item.id_rolper
										</td>
										<td>
											@item.rol_desc
										</td>
										<td>
											@item.menuprin_desc
										</td>
										<td>
											@item.submenu_desc
										</td>
										<td>
											@if(item.rolper_act)
											{
												<input name="check"  type="checkbox" value=@item.id_rolper checked="checked" />
											}
											else
											{
												<input name="check" type="checkbox" value=@item.id_rolper />
											}										
										</td>
									</tr>
								}
							</tbody>
						</table>
					</div>
					<div class="tab-pane fade" id="nav-caja" role="tabpanel">
						<table id="tblcaja" class="table table-striped table-bordered" style="width: 100%">
							<thead>
								<tr>
									<th class="d-none">
										id_rolper
									</th>
									<th>
										Rol
									</th>
									<th>
										Menu
									</th>
									<th>
										Submenu
									</th>
									<th>
										Activo / Inactivo
									</th>
								</tr>
							</thead>							
							<tbody>
								@foreach (var item in ViewBag.caja)
								{
									<tr>
										<td class="d-none check">
											@item.id_rolper
										</td>
										<td>
											@item.rol_desc
										</td>
										<td>
											@item.menuprin_desc
										</td>
										<td>
											@item.submenu_desc
										</td>
										<td>
											@if(item.rolper_act)
											{
												<input name="check"  type="checkbox" value=@item.id_rolper checked="checked" />
											}
											else
											{
												<input name="check" type="checkbox" value=@item.id_rolper />
											}										
										</td>
									</tr>
								}
							</tbody>
						</table>
					</div>
                 </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
	<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css"></script>
	<script type="text/javascript">
		$(document).ready(function () {
			 $('#tbladmin').DataTable({
                "pageLength": 20,
                "language": {
                    "lengthMenu": "Mostrar _MENU_ registros por pagina",
                    "zeroRecords": "No se encontraron registros",
                    "info": "Mostrar pagina _PAGE_ de _PAGES_",
                    "infoEmpty": "No se encontraron registros",
                    "infoFiltered": "(filtrado de _MAX_ registros totales)",
                    "search": "Buscar:",
                    "paginate": {
                        "next": "siguiente",
                        "previous": "Anterior"
                    }
                },
                "scrollX": true,
                "responsive": true
             });

			 $('#tblplani').DataTable({
                "pageLength": 20,
                "language": {
                    "lengthMenu": "Mostrar _MENU_ registros por pagina",
                    "zeroRecords": "No se encontraron registros",
                    "info": "Mostrar pagina _PAGE_ de _PAGES_",
                    "infoEmpty": "No se encontraron registros",
                    "infoFiltered": "(filtrado de _MAX_ registros totales)",
                    "search": "Buscar:",
                    "paginate": {
                        "next": "siguiente",
                        "previous": "Anterior"
                    }
                },
                "scrollX": true,
                "responsive": true
             });

			 $('#tblcaja').DataTable({
                "pageLength": 20,
                "language": {
                    "lengthMenu": "Mostrar _MENU_ registros por pagina",
                    "zeroRecords": "No se encontraron registros",
                    "info": "Mostrar pagina _PAGE_ de _PAGES_",
                    "infoEmpty": "No se encontraron registros",
                    "infoFiltered": "(filtrado de _MAX_ registros totales)",
                    "search": "Buscar:",
                    "paginate": {
                        "next": "siguiente",
                        "previous": "Anterior"
                    }
                },
                "scrollX": true,
                "responsive": true
             });
			 
			 
			 $("#asignar").click(function(){
				var menus = new Array();    
				var Idrol = $("#Idrol2").val() 
				$('#checkid input[type=checkbox]').each(function(){
					if (this.checked) {
						menus.push($(this).val());
					}
				}); 
				if (menus != ''){
					 var menulist = {
						 oMenus: menus
					}					
					$.ajax({
						url: "@Url.Action("otorgar", "MDRol_Permisos")",
						traditional: true,
						data: { 'menus': menus, 'Idrol': Idrol },
						success: function(result){										 
							swal('Mensaje de confirmacion', 'Carga eliminada', 'success');
							
						}
					});			
				}					  
				else{
					alert('Debes seleccionar al menos una opción.');
				}
					
				return false;
			 });         	
        });
	</script>
}